name: Test & Build

on:
  push:
    branches: [ 'develop', 'master' ]
  pull_request:
    branches: [ 'develop', 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout branch ${{ github.ref_name }}
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Setup Nest CLI
        run: yarn global add @nestjs/cli
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Building on ${{ github.ref_type }} ${{ github.ref_name }}
        run: yarn prebuild & yarn build
      - name: Run Unit Tests
        run: yarn test
      - name: Run e2e Tests
        run: yarn test:e2e

